image: node:18

stages:
  - install
  - build

frontend_install:
  stage: install
  script:
    - cd frontend
    - npm install

frontend_build:
  stage: build
  script:
    - cd frontend
    - npm run build